joint_state_controller:
  type: joint_state_controller/JointStateController 
  publish_rate: 50.0
# Position Controllers --------------------------------------- 
joint1_position_controller:
  type: effort_controllers/JointPositionController 
  joint: joint_1
  pid: {p: 50000.0, i: 500.0, d: 1000.0}
joint2_position_controller:
  type: effort_controllers/JointPositionController 
  joint: joint_2
  pid: {p: 12000.0, i: 400, d: 1000.0}
joint3_position_controller:
  type: effort_controllers/JointPositionController 
  joint: joint_3
  pid: {p: 11000.0, i: 400, d: 1000.0}
joint4_position_controller:
  type: effort_controllers/JointPositionController 
  joint: tool_link
  pid: {p: 15000.0, i: 400, d: 1000.0}
joint5_position_controller:
  type: effort_controllers/JointPositionController
  joint: finger
  pid: {p: 40000.0, i: 200, d: 10}
joint6_position_controller:
  type: effort_controllers/JointPositionController 
  joint: noa
  pid: {p: 20000.0, i: 500, d: 0}
